In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([79, 77, 39, 28,  7, 86,  7, 58, 91, 17, 23, 52, 88, 40, 79])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[12, 37, 24, 36],
       [62, 56, 77, 47],
       [36, 10, 59, 50],
       [64, 11, 63, 59],
       [52, 72, 65, 78],
       [19, 24, 33, 72]])

In [3]:
np.sort(a)[::-1]

array([91, 88, 86, 79, 79, 77, 58, 52, 40, 39, 28, 23, 17,  7,  7])

In [4]:
np.sort(b,axis=0)

array([[12, 10, 24, 36],
       [19, 11, 33, 47],
       [36, 24, 59, 50],
       [52, 37, 63, 59],
       [62, 56, 65, 72],
       [64, 72, 77, 78]])

In [5]:
# code
np.append(a,200)

array([ 79,  77,  39,  28,   7,  86,   7,  58,  91,  17,  23,  52,  88,
        40,  79, 200])

In [6]:
b

array([[12, 37, 24, 36],
       [62, 56, 77, 47],
       [36, 10, 59, 50],
       [64, 11, 63, 59],
       [52, 72, 65, 78],
       [19, 24, 33, 72]])

In [7]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[1.20000000e+01, 3.70000000e+01, 2.40000000e+01, 3.60000000e+01,
        5.82764416e-01],
       [6.20000000e+01, 5.60000000e+01, 7.70000000e+01, 4.70000000e+01,
        1.31360267e-01],
       [3.60000000e+01, 1.00000000e+01, 5.90000000e+01, 5.00000000e+01,
        9.39508633e-01],
       [6.40000000e+01, 1.10000000e+01, 6.30000000e+01, 5.90000000e+01,
        6.26946139e-02],
       [5.20000000e+01, 7.20000000e+01, 6.50000000e+01, 7.80000000e+01,
        7.48139570e-01],
       [1.90000000e+01, 2.40000000e+01, 3.30000000e+01, 7.20000000e+01,
        8.64712433e-01]])

In [8]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [10]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [12]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [13]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [14]:
# code
a.shape

(15,)

In [15]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [16]:
np.expand_dims(a,axis=1)

array([[79],
       [77],
       [39],
       [28],
       [ 7],
       [86],
       [ 7],
       [58],
       [91],
       [17],
       [23],
       [52],
       [88],
       [40],
       [79]])

In [17]:
a

array([79, 77, 39, 28,  7, 86,  7, 58, 91, 17, 23, 52, 88, 40, 79])

In [18]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  1,  5,  7,  8, 11, 12, 14]),)

In [19]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0,  0, 39, 28,  7,  0,  7,  0,  0, 17, 23,  0,  0, 40,  0])

In [20]:
np.where(a%2 == 0,0,a)

array([79, 77, 39,  0,  7,  0,  7,  0, 91, 17, 23,  0,  0,  0, 79])

In [21]:
# code
a

array([79, 77, 39, 28,  7, 86,  7, 58, 91, 17, 23, 52, 88, 40, 79])

In [22]:
np.argmax(a)

np.int64(8)

In [23]:
np.argmax(b,axis=0)

array([3, 4, 1, 4])

In [24]:
np.argmax(b,axis=1)

array([1, 2, 2, 0, 3, 3])

In [25]:
# np.argmin
np.argmin(a)

np.int64(4)

In [26]:
a

array([79, 77, 39, 28,  7, 86,  7, 58, 91, 17, 23, 52, 88, 40, 79])

In [27]:
np.cumsum(a)

array([ 79, 156, 195, 223, 230, 316, 323, 381, 472, 489, 512, 564, 652,
       692, 771])

In [28]:
np.cumsum(b,axis=1)

array([[ 12,  49,  73, 109],
       [ 62, 118, 195, 242],
       [ 36,  46, 105, 155],
       [ 64,  75, 138, 197],
       [ 52, 124, 189, 267],
       [ 19,  43,  76, 148]])

In [29]:
np.cumsum(b)

array([  12,   49,   73,  109,  171,  227,  304,  351,  387,  397,  456,
        506,  570,  581,  644,  703,  755,  827,  892,  970,  989, 1013,
       1046, 1118])

In [30]:
# np.cumprod
np.cumprod(a)

array([                  79,                 6083,               237237,
                    6642636,             46498452,           3998866872,
                27992068104,        1623539950032,      147742135452912,
           2511616302699504,    57767174962088592,  3003893098028606784,
        6088175594583674368,  3719350825122803712, -1319189994651332608])

In [31]:
np.percentile(a,50)

np.float64(52.0)

In [32]:
np.median(a)

np.float64(52.0)

In [33]:
np.histogram(a,bins=[0,50,100])

(array([7, 8]), array([  0,  50, 100]))

In [34]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [35]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([40])

In [36]:
np.flip(a)

array([79, 40, 88, 52, 23, 17, 91, 58,  7, 86,  7, 28, 39, 77, 79])

In [37]:
np.flip(b,axis=1)

array([[36, 24, 37, 12],
       [47, 77, 56, 62],
       [50, 59, 10, 36],
       [59, 63, 11, 64],
       [78, 65, 72, 52],
       [72, 33, 24, 19]])

In [38]:
np.put(a,[0,1],[110,530])

In [39]:
np.delete(a,[0,2,4])

array([530,  28,  86,   7,  58,  91,  17,  23,  52,  88,  40,  79])

In [40]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [41]:
np.intersect1d(m,n)

array([3, 4, 5])

In [42]:
np.setdiff1d(n,m)

array([6, 7])

In [43]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [44]:
m[np.in1d(m,1)]

/var/folders/g6/6hcjlt9n5rq08sjpd07q0lf40000gn/T/ipykernel_24981/524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

In [45]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 39, 28, 25, 75, 25, 58, 75, 25, 25, 52, 75, 40, 75])